name: printobs
channels:
  - conda-forge
dependencies:
  - python<3.11
  - matplotlib>=3.1
  - numpy>=1.15.4
  - scipy>=1.2.0
  - pandas
  - python-dotenv
  - pyyaml
  - requests
  - xarray
  - pip
  - pip:
    - pytest
